### ISSUE TITLE
bugs in the build/display process

### ISSUE THREAD

**Issue by bilderbuchi** [benben/oftesting#1]
hey @benben!
Thanks for the latest improvements, it's getting nicer and nicer to work with the results. I thought I'd report bugs here, instead of over the list, is that alright with you?
- ~~non-OSX systems try to compile some osx examples.~~
- ~~some parsing issue I guess: in testrun - show details, in the test matrix/table, clicking on the colored dots leads to a github 404 page. the url is e.g. `http://videosynthesis.net/oftesting/testruns/20121117_172351-tag_0073/Debian%206.0.5%20GNOME%2032bit/tests/install_codeblocks.sh`~~
- http://apt.jenslody.de stable Release is still missing a key on Debian. Don't know what's up with that, but it's been like that for more than one test.
- remove codeblocks bleeding edge installation from setup scripts to solve the above issue. see  openframeworks/openFrameworks#1707

**Comment by benben** [comment]
hi @bilderbuchi,

thanks for your report!
point 1 & 2 are fixed now. point 3 is an openFrameworks issue, I will leave this ticket open until we fixed it there.

**Comment by bilderbuchi** [comment]
thank you! 
do we even need the jenslody repo? I mean, I think this is just a leftover from when codeblocks 9 or 10 was out, but the distributions still shipped 8, and we needed some features/fixes from 9. couldn't we just drop that part, or do we still rely on bleeding-edge C::B? @arturoc, do you know?

**Comment by bilderbuchi** [comment]
btw, 0 errors except for debian! :dancer: congrats, nice work!
apparently it's high time I continue work on eliminating all the warnings in the examples :D

one thing I noticed: On MacOS, warning count is zero, we still need to find a way to enable those properly. see end of discussion in https://github.com/openframeworks/openFrameworks/issues/1466

**Comment by arturoc** [comment]
it's been a while since i don't test debian but it shouldn't be necessary anymore since codeblocks in the default repos should be 10.05 as in ubuntu

**Comment by bilderbuchi** [comment]
ok, thanks. i've opened an issue here: https://github.com/openframeworks/openFrameworks/issues/1707

**Comment by benben** [comment]
Debian install dep scripts worked in the last run, I close this for now! thanks again!

http://videosynthesis.net/oftesting/testruns/20130123_120800-standard_run/vagrant-debian6.0.5-gnome-32bit/tests/install_dependencies.sh/

**Comment by bilderbuchi** [comment]
great! I thank you!
