### ISSUE TITLE
Calculation of passed/warning/error count in overview "black bar" is wrong

### ISSUE THREAD

**Issue by bilderbuchi** [benben/oftesting#2]
On the [home page](http://videosynthesis.net/oftesting/) of OFTesting, in the black bar summary for every test run, the number of passed/warning/error counts is wrong - it's not a sum(mary) over all tests, but picks results from one OS, mostly MacOS or Debian.

**Comment by benben** [comment]
I always wondered what that numbers mean :smiley_cat: 

I' thinking of restructuring the front page completely but doesn't have a good idea yet. So if the numbers survive, I will fix it.

**Comment by bilderbuchi** [comment]
I always thought that they were supposed to be the sum of all tests that passed/warned/errored, but in retrospect this doesn't make too much sense if the number of tested OSes varies.

**Comment by benben** [comment]
You're right. This was what I intended. It is, like everything else, WIP. I
thought of a percentage or something like that
